services:
  postgres:
    image: postgres:15-alpine
    container_name: telcomanager_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-stock_intervention}
    volumes:
      - /opt/phonetic_telco-manager/data/db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-postgres} -d $${DB_NAME:-stock_intervention}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: always

  app:
    image: phonetic76/telcomanager-app:latest
    container_name: telcomanager_app
    environment:
      DATABASE_URL: postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-stock_intervention}?schema=public
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-supersecretkey}
      NODE_ENV: production
      # Push Notifications (Générés via 'npx web-push generate-vapid-keys')
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-BJmQzz733_Nkbxwn1aMsP1yVWzdFw1TKhYsER_qI2Gh_0HMBY3299ufHIbzsOMfTcTD-ybLlwQA0WMSsyg920eM}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-6sOLs1-4ll7aVy_8F73mvLXdnfZphDqNVfKwGz7Z9cg}
      VAPID_SUBJECT: ${VAPID_SUBJECT:-mailto:np@phone-tic.fr}
      # UNYC Sync Configuration (Requis pour la synchro)
      UNYC_BASE_URL: ${UNYC_BASE_URL:-https://atlas-public-api.web.production.unyc.io}
      UNYC_IAM_URL: ${UNYC_IAM_URL:-https://accounts.unyc.io/realms/production}
      UNYC_CLIENT_ID: ${UNYC_CLIENT_ID:-public-api}
      UNYC_USERNAME: ${UNYC_USERNAME}
      UNYC_PASSWORD: ${UNYC_PASSWORD}
      ATLAS_IP_LINKS_URL: ${ATLAS_IP_LINKS_URL:-https://atlas.unyc.io/lien}
      ATLAS_USERNAME: ${ATLAS_USERNAME:-np@phone-tic.fr}
      ATLAS_PASSWORD: ${ATLAS_PASSWORD:-!QC5Rx#U@c@4wR}
      ATLAS_TOTP_URI: ${ATLAS_TOTP_URI:-otpauth://totp/unyc:nplacide?secret=KBGTOU3LPBWVAY2KKJQVMMSWGEYU65TT&digits=6&algorithm=SHA1&issuer=unyc&period=30}
      # Optionnel: Reset DB au démarrage (true/false)
      # SEED_ON_START: "false"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - uploads_data:/app/uploads
    restart: always

  caddy:
    image: phonetic76/caddy-duckdns:latest
    container_name: telcomanager_caddy
    ports:
      - "80:80"
      - "8081:443"
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN:-}
    volumes:
      - /opt/phonetic_telco-manager/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  uploads_data:
  caddy_data:
  caddy_config:
