services:
  postgres:
    image: postgres:15-alpine
    container_name: telcomanager_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-stock_intervention}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app_network
    restart: always

  app:
    image: phonetic76/telcomanager-app:latest
    build:
      context: .
      dockerfile: Dockerfile.combined
    container_name: telcomanager_app
    environment:
      DATABASE_URL: postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-stock_intervention}?schema=public
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-supersecretkey}
      NODE_ENV: production
      # Push Notifications (Générés via 'npx web-push generate-vapid-keys')
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-BJmQzz733_Nkbxwn1aMsP1yVWzdFw1TKhYsER_qI2Gh_0HMBY3299ufHIbzsOMfTcTD-ybLlwQA0WMSsyg920eM}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-6sOLs1-4ll7aVy_8F73mvLXdnfZphDqNVfKwGz7Z9cg}
      VAPID_SUBJECT: ${VAPID_SUBJECT:-mailto:np@phone-tic.fr}
      # UNYC Sync Configuration (Requis pour la synchro)
      UNYC_BASE_URL: ${UNYC_BASE_URL:-https://atlas-public-api.web.production.unyc.io}
      UNYC_IAM_URL: ${UNYC_IAM_URL:-https://accounts.unyc.io/realms/production}
      UNYC_CLIENT_ID: ${UNYC_CLIENT_ID:-public-api}
      UNYC_USERNAME: ${UNYC_USERNAME}
      UNYC_PASSWORD: ${UNYC_PASSWORD}
      ATLAS_IP_LINKS_URL: ${ATLAS_IP_LINKS_URL:-https://atlas.unyc.io/lien}
      ATLAS_USERNAME: ${ATLAS_USERNAME:-np@phone-tic.fr}
      ATLAS_PASSWORD: ${ATLAS_PASSWORD:-!QC5Rx#U@c@4wR}
      ATLAS_TOTP_URI: ${ATLAS_TOTP_URI:-otpauth://totp/unyc:nplacide?secret=KBGTOU3LPBWVAY2KKJQVMMSWGEYU65TT&digits=6&algorithm=SHA1&issuer=unyc&period=30}
      # Optionnel: Reset DB au démarrage (true/false)
      # SEED_ON_START: "false"
    ports:
      - "8081:3000"
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - uploads_data:/app/uploads
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:
